### ISSUE TITLE
Listing Filter Added - Shouldn't Fire on PLP Load

### ISSUE THREAD

**Issue by jasonegan** [searchdiscovery/mohawk-flooring-dl-spec#29] opened 2021-04-09 17:14 UTC
At this time when you browse to a PLP, the following events are firing:

![image](https://user-images.githubusercontent.com/72522616/114216814-6747b080-9935-11eb-8070-e575b75ff0e2.png)

The "Listing Filter Added" event should only fire when a visitor actively adds a filter by their own actions. So, this event should not fire on the initial view of [this page](https://staging.pergoflooring.com/shop/laminate?installation=&look=&page=1&shade=).

**Comment by rmessickSDI** [comment] 2021-04-27 18:08
Does not load on initial page load.
![image](https://user-images.githubusercontent.com/78565036/116290627-4b2b7800-a759-11eb-8809-a41250b7804c.png)

**Comment by rmessickSDI** [comment] 2021-04-27 18:17
Ok looked at this one again.  This page should not fire "Listing Filter Added" when you first load it.  
https://staging.pergoflooring.com/shop?installation=&look=&page=1&shade=

But if you switch the first dropdown to example laminate it switches the url and load the virtual page again without "Listing Filter Added".  Which I think we need to know if they changed that filter.  

@jasonegan We will need to walk through how we will want to handle this.  The first dropdown in filter changed the page and we do not get the "Listing Filter Added".

**Comment by jasonegan** [comment] 2021-04-28 13:10
@rmessickSDI Agreed. It looks like the first dropdown here for filtering is not firing the Listing Filter Added event at all. Even if you select a second, it is not in the list of currently applied filters. Nor if you change the first after selecting a second does the first fire.

**Comment by jasonegan** [comment] 2021-04-28 13:11
@savithanuguri Assigning back to you as it looks like the first drop down on PLP is not firing the Listing Filter Added event when it is changed by the visitor.

**Comment by rmessickSDI** [comment] 2021-04-29 19:24
@savithanuguri Is this issue fixed?  Can you add to comment when it is fixed so we know to go back and test?

**Comment by nate-wolfe** [comment] 2021-04-29 19:32
@rmessickSDI Sort of. The code to fix it was merged into develop yesterday, and just hasn't been merged to staging yet. Apologies for the confusion, I think a few of these tickets are in the same situation.

**Comment by savithanuguri** [comment] 2021-05-05 17:50
@rmessickSDI , Tested in a staging environment.

![image](https://user-images.githubusercontent.com/82102160/117186456-d71c5000-ada8-11eb-9b3f-72d63af2b259.png)

**Comment by rmessickSDI** [comment] 2021-05-05 20:38
Ok it looks like when you are on:
https://staging.pergoflooring.com/shop
and click the first dropdown it switched pages to:
https://staging.pergoflooring.com/shop/laminate
https://staging.pergoflooring.com/shop/hardwood
https://staging.pergoflooring.com/shop/rigidvinyl

So everything looks good except if you are on one of the dropdown pages and go back to `Type` it does not fire removed filter event.  I think that may be limitation on how it is built.  @savithanuguri @nate-wolfe Can you confirm?

@jasonegan Do you want to follow up with Jake on this to make him aware.

**Comment by savithanuguri** [comment] 2021-05-05 20:42
@rmessickSDI, default loading of the PLP page is with any one of the types(Laminate, Hardwood or Vinyl plank)

**Comment by ryanAtSdi** [comment] 2021-05-07 16:21
@savithanuguri - I want to confirm that filter removed should NOT fire when removing the Type filter on PLP. If that's the expected behavior, we can close this ticket out.

**Comment by savithanuguri** [comment] 2021-05-07 16:42
@ryanAtSdi, In the PLP type filter, if we change the type from laminate to hardwood, the Listing Filter Added event is firing. We cannot remove or reset to Type.

**Closed** 2021-05-07 16:46 UTC
Labels: DL Review 1, DL Review 2
